name: C Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libcriterion-dev valgrind

      - name: Build and run tests
        run: make test
